name: Angular Github CI
on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install FE Dependencies
        if: steps.cache-nodemodules.output.cache-hit != 'true'
        run: |
          cd redqueen-app
          npm ci
      
      - name: Build FE
        run: |
          cd redqueen-app
          npm run build:dev
      
      - name: Lint FE
        run: |
          cd redqueen-app
          npm run lint

      - name: Install data API dependencies
        run: |
          cd redqueen-backend/redqueen-data
          npm ci
      
      - name: Build data API
        run: |
          cd redqueen-backend
          npm run build --workspace @redqueen-backend/redqueen-data

      - name: Install BE Dependencies
        run: |
          cd redqueen-backend
          npm ci
    
      - name: Lint BE
        run: |
          cd redqueen-backend
          npm run format --workspaces
      
      - name: Build REST API and Daemon
        run: |
          cd redqueen-backend
          npm run build --workspace @redqueen-backend/redqueen-api
          npm run build --workspace @redqueen-backend/redqueen
